name: Tests Run

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '17.x'
      - run: npm install
      - run: npm run build --if-present
      - name: Run Tests
        run: npm run test
        working-directory: ./frontend
        run: npm test
